// Generated by sync.py on 2026-05-11T21:09:43+00:00
// Do not edit manually — run the "Sync Playlist" workflow to regenerate.
window.TRACK_DATA = {
  "playlist_name": "Despaciti ripasso",
  "playlist_id": "7BmgkQ5X7yCd1g9Ci4pB9x",
  "generated_at": "2026-05-11T21:09:43+00:00",
  "tracks": [
    {
      "track_id": "0lIoY4ZQsdn5QzhraM9o9u",
      "uri": "spotify:track:0lIoY4ZQsdn5QzhraM9o9u",
      "title": "Because the Night",
      "artist": "Patti Smith",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273a28eabe111f67a386e75a31a",
      "duration_ms": 204800,
      "valence": 0.6668061017990112,
      "energy": 0.7137083411216736
    },
    {
      "track_id": "3HMY0r2BAdpasXMY8rseR0",
      "uri": "spotify:track:3HMY0r2BAdpasXMY8rseR0",
      "title": "Too Sweet",
      "artist": "Hozier",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273be392334d99f82bc410cb239",
      "duration_ms": 251424,
      "valence": 0.5157116651535034,
      "energy": 0.50361168384552
    },
    {
      "track_id": "0UFDKFqW2oGspYeYqo9wjA",
      "uri": "spotify:track:0UFDKFqW2oGspYeYqo9wjA",
      "title": "Bleed It Out",
      "artist": "Linkin Park",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b2736e996745f2c7b8036abef213",
      "duration_ms": 164426,
      "valence": 0.6564863324165344,
      "energy": 0.7827329635620117
    },
    {
      "track_id": "4UVKy0DI1hOlL8xF99Ba5j",
      "uri": "spotify:track:4UVKy0DI1hOlL8xF99Ba5j",
      "title": "Any Way You Want It (2024 Remaster)",
      "artist": "Journey",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b27370b5c118e7ac6b8a457e81e8",
      "duration_ms": 203725,
      "valence": 0.4881824254989624,
      "energy": 0.5915012359619141
    },
    {
      "track_id": "6CCbKMOTlcYvHd9f8Sm3qm",
      "uri": "spotify:track:6CCbKMOTlcYvHd9f8Sm3qm",
      "title": "Diventerai una star",
      "artist": "Finley",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b2739bcbfe767d771b7971c40371",
      "duration_ms": 188480,
      "valence": 0.592346727848053,
      "energy": 0.6621221899986267
    },
    {
      "track_id": "4kbj5MwxO1bq9wjT5g9HaA",
      "uri": "spotify:track:4kbj5MwxO1bq9wjT5g9HaA",
      "title": "Shut Up and Dance",
      "artist": "WALK THE MOON",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273fc39eb9eb3f3824a58f338dc",
      "duration_ms": 199080,
      "valence": 0.5438891649246216,
      "energy": 0.6721500754356384
    },
    {
      "track_id": "22skzmqfdWrjJylampe0kt",
      "uri": "spotify:track:22skzmqfdWrjJylampe0kt",
      "title": "Can't Hold Us (feat. Ray Dalton)",
      "artist": "Macklemore, Ryan Lewis, Macklemore & Ryan Lewis, Ray Dalton",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b2732a6b364528b128a4a17d100d",
      "duration_ms": 258431,
      "valence": 0.570543646812439,
      "energy": 0.760418713092804
    },
    {
      "track_id": "5RKQ5NdjSh2QzD4MaunT91",
      "uri": "spotify:track:5RKQ5NdjSh2QzD4MaunT91",
      "title": "Don't Stop Believin' (2022 Remaster)",
      "artist": "Journey",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b27323290120a609a65e14cfe018",
      "duration_ms": 249600,
      "valence": 0.5240759253501892,
      "energy": 0.5761221647262573
    },
    {
      "track_id": "4mn2kNTqiGLwaUR8JdhJ1l",
      "uri": "spotify:track:4mn2kNTqiGLwaUR8JdhJ1l",
      "title": "House of the Rising Sun",
      "artist": "The Animals",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273015c484a7aca592df1a77828",
      "duration_ms": 269906,
      "valence": 0.5286133289337158,
      "energy": 0.5906619429588318
    },
    {
      "track_id": "63CSozvYUEudPp12679UVF",
      "uri": "spotify:track:63CSozvYUEudPp12679UVF",
      "title": "Don't Worry (with Ray Dalton) - Radio Edit",
      "artist": "Madcon, Ray Dalton",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273ff1831eb17c7a83741be4d1b",
      "duration_ms": 214789,
      "valence": 0.7289605736732483,
      "energy": 0.7490661144256592
    },
    {
      "track_id": "1SKPmfSYaPsETbRHaiA18G",
      "uri": "spotify:track:1SKPmfSYaPsETbRHaiA18G",
      "title": "Somewhere Only We Know",
      "artist": "Keane",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b2737d6cd95a046a3c0dacbc7d33",
      "duration_ms": 237146,
      "valence": 0.5489099621772766,
      "energy": 0.702965497970581
    },
    {
      "track_id": "6ZQf7QhN9jCwyIGOO9rOLb",
      "uri": "spotify:track:6ZQf7QhN9jCwyIGOO9rOLb",
      "title": "Ipocondria",
      "artist": "Giancane, Rancore",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b27368fb44e77371679aa2c05525",
      "duration_ms": 227594,
      "valence": 0.4757292866706848,
      "energy": 0.7055979371070862
    },
    {
      "track_id": "2SiXAy7TuUkycRVbbWDEpo",
      "uri": "spotify:track:2SiXAy7TuUkycRVbbWDEpo",
      "title": "You Shook Me All Night Long",
      "artist": "AC/DC",
      "album_art_url": "https://i.scdn.co/image/ab67616d0000b273ff191d7fbdb5a13eaf84132b",
      "duration_ms": 210328,
      "valence": 0.6365479230880737,
      "energy": 0.6619611382484436
    }
  ]
};
