#!/usr/bin/env python3
"""
sync.py — Phase 1 of the DnD Soundtrack Manager

Fetches a Spotify playlist, downloads 30-second preview clips, extracts
valence/energy with Essentia, and writes the results to webapp/data.js.
Also generates webapp/js/config.js (contains clientId — not a secret).

Credential resolution order:
  1. Environment variables (used by GitHub Actions):
       SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_PLAYLIST_ID
  2. config.json in the same directory as this script (local dev)
  3. CLI --playlist overrides the playlist ID from either source

redirectUri resolution:
  - The webapp detects its own URL at runtime (window.location)
  - Works automatically for both GitHub Pages and local dev

Usage:
  python sync.py
  python sync.py --playlist <url-or-id>
  python sync.py --force-reanalyze
  python sync.py --local              # also start a local HTTP server
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
import time
import webbrowser
from pathlib import Path

from tqdm import tqdm

# Ensure src/ is importable regardless of the working directory.
REPO_ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(REPO_ROOT))

from src.data_manager import read_data_js, update_track, write_data_js
from src.downloader import cleanup, download
from src.feature_extractor import analyze
from src.spotify_client import SpotifyClient


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

def load_config() -> dict:
    """Return credentials merged from environment and config.json."""
    config: dict = {}

    config_path = REPO_ROOT / "config.json"
    if config_path.exists():
        with config_path.open(encoding="utf-8") as f:
            config = json.load(f)

    # Environment variables take precedence over config.json.
    if os.environ.get("SPOTIFY_CLIENT_ID"):
        config["client_id"] = os.environ["SPOTIFY_CLIENT_ID"]
    if os.environ.get("SPOTIFY_CLIENT_SECRET"):
        config["client_secret"] = os.environ["SPOTIFY_CLIENT_SECRET"]
    if os.environ.get("SPOTIFY_PLAYLIST_ID"):
        config["playlist_id"] = os.environ["SPOTIFY_PLAYLIST_ID"]
    if os.environ.get("SPOTIFY_REFRESH_TOKEN"):
        config["refresh_token"] = os.environ["SPOTIFY_REFRESH_TOKEN"]

    return config


# ---------------------------------------------------------------------------
# config.js generation
# ---------------------------------------------------------------------------

_CONFIG_JS_TEMPLATE = """\
// Generated by sync.py — do not edit manually.
window.CONFIG = {{
  clientId: {client_id},
  redirectUri: window.location.origin + window.location.pathname.replace(/index\\.html$/, ""),
  scopes: "streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state",
  playerName: "DnD Player",
  sigma: 0.15,
  recentlyPlayedSize: 5,
}};
"""


def write_config_js(webapp_dir: Path, client_id: str) -> None:
    config_js = webapp_dir / "js" / "config.js"
    config_js.parent.mkdir(parents=True, exist_ok=True)
    content = _CONFIG_JS_TEMPLATE.format(
        client_id=json.dumps(client_id),
    )
    config_js.write_text(content, encoding="utf-8")
    print(f"  Written: {config_js.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Local HTTP server (--local flag)
# ---------------------------------------------------------------------------

def _port_in_use(port: int) -> bool:
    """Return True if something is already listening on localhost:{port}."""
    import urllib.request
    try:
        urllib.request.urlopen(f"http://localhost:{port}/", timeout=1)
        return True
    except Exception:
        return False


def start_local_server(webapp_dir: Path, port: int) -> None:
    """Launch a detached static HTTP server serving webapp_dir on port."""
    if _port_in_use(port):
        print(f"  Port {port} already in use — skipping server launch.")
        return

    kwargs: dict = dict(
        cwd=str(webapp_dir),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    if sys.platform == "win32":
        kwargs["creationflags"] = (
            subprocess.CREATE_NEW_PROCESS_GROUP | subprocess.DETACHED_PROCESS  # type: ignore[attr-defined]
        )
    else:
        kwargs["start_new_session"] = True

    subprocess.Popen([sys.executable, "-m", "http.server", str(port)], **kwargs)
    print(f"  Started static server at http://localhost:{port}")


# ---------------------------------------------------------------------------
# Main sync flow
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Sync Spotify playlist for DnD Soundtrack Manager")
    parser.add_argument("--playlist", metavar="URL_OR_ID", help="Override playlist ID from config/env")
    parser.add_argument("--force-reanalyze", action="store_true", help="Re-analyze all tracks even if cached")
    parser.add_argument("--local", action="store_true", help="Start a local HTTP server after sync (requires Linux/macOS/WSL)")
    args = parser.parse_args()

    config = load_config()

    # Validate credentials.
    for key in ("client_id", "client_secret"):
        if not config.get(key):
            sys.exit(
                f"ERROR: {key!r} not found.\n"
                "Set SPOTIFY_CLIENT_ID / SPOTIFY_CLIENT_SECRET env vars,\n"
                "or copy config.json.example → config.json and fill in your credentials."
            )

    playlist_id = args.playlist or config.get("playlist_id")
    if not playlist_id:
        sys.exit(
            "ERROR: No playlist ID provided.\n"
            "Use --playlist <url-or-id>, set SPOTIFY_PLAYLIST_ID, or add it to config.json."
        )

    webapp_dir = REPO_ROOT / "webapp"
    models_dir = REPO_ROOT / "models"
    temp_base = Path(tempfile.gettempdir()) / "dnd_analysis"
    data_js_path = webapp_dir / "data.js"
    port = config.get("port", 8080)

    print("DnD Soundtrack Manager — sync")
    print(f"  Playlist: {playlist_id}")

    # ------------------------------------------------------------------
    # 1. Fetch playlist metadata from Spotify
    # ------------------------------------------------------------------
    print("\nFetching playlist from Spotify...")
    client = SpotifyClient(
        config["client_id"],
        config["client_secret"],
        refresh_token=config.get("refresh_token"),
    )
    playlist_name = client.get_playlist_name(playlist_id)
    remote_tracks = client.get_playlist_tracks(playlist_id)
    print(f"  Playlist: '{playlist_name}' — {len(remote_tracks)} tracks")

    if not remote_tracks:
        sys.exit("ERROR: Playlist is empty or could not be fetched.")

    # ------------------------------------------------------------------
    # 2. Load existing data.js cache
    # ------------------------------------------------------------------
    cache = read_data_js(data_js_path)
    if cache:
        print(f"  Found cached data for {len(cache)} tracks in data.js")

    # ------------------------------------------------------------------
    # 3. Build the full track list (merge cache + remote metadata)
    # ------------------------------------------------------------------
    # Start with a fresh write so any removed tracks are dropped.
    tracks_to_write: list[dict] = []
    for t in remote_tracks:
        if t["track_id"] in cache and not args.force_reanalyze:
            tracks_to_write.append(cache[t["track_id"]])
        else:
            tracks_to_write.append(t)  # valence/energy to be filled in below

    write_data_js(data_js_path, playlist_name, playlist_id, tracks_to_write)

    # ------------------------------------------------------------------
    # 4. Analyze tracks that don't have valence/energy yet
    # ------------------------------------------------------------------
    to_analyze = [
        t for t in remote_tracks
        if args.force_reanalyze
        or "valence" not in cache.get(t["track_id"], {})
        or cache[t["track_id"]].get("download_failed")
    ]

    if not to_analyze:
        print("\nAll tracks already analyzed — nothing to do.")
    else:
        print(f"\nAnalyzing {len(to_analyze)} track(s)...")
        for track in tqdm(to_analyze, unit="track"):
            tid = track["track_id"]
            tqdm.write(f"  ↓  {track['title']} — {track['artist']}")

            # Download
            mp3_path = download(tid, track["title"], track["artist"], temp_base)

            if mp3_path is None:
                tqdm.write(f"  ✗  Download failed — skipping")
                update_track(data_js_path, tid, {"download_failed": True})
                continue

            # Analyze
            result = analyze(mp3_path, models_dir)

            # Clean up immediately — don't keep audio files on disk
            cleanup(temp_base / tid)

            if result is None:
                tqdm.write(f"  ✗  Analysis failed — skipping")
                update_track(data_js_path, tid, {"analysis_failed": True})
                continue

            valence, energy = result
            tqdm.write(f"  ✓  valence={valence:.3f}  energy={energy:.3f}")
            update_track(data_js_path, tid, {"valence": valence, "energy": energy})

        print(f"\ndata.js written: {data_js_path.relative_to(REPO_ROOT)}")

    # ------------------------------------------------------------------
    # 5. Write webapp/js/config.js
    # ------------------------------------------------------------------
    print("\nWriting config.js...")
    write_config_js(webapp_dir, config["client_id"])

    # ------------------------------------------------------------------
    # 6. Optionally start local server + open browser
    # ------------------------------------------------------------------
    if args.local:
        print(f"\nStarting local server on port {port}...")
        start_local_server(webapp_dir, port)
        time.sleep(0.5)  # brief pause so the server is ready before the browser hits it
        webbrowser.open(f"http://localhost:{port}")

    print("\nSync complete.")
    if not args.local and not os.environ.get("GITHUB_PAGES_URL"):
        print(f"To serve the webapp locally:\n  cd webapp && python -m http.server {port}")


if __name__ == "__main__":
    main()
