// This file is generated by sync.py / the GitHub Actions workflow.
// Do not edit manually.
window.CONFIG = {
  clientId: "",
  redirectUri: "http://localhost:8080",
  scopes: "streaming user-read-email user-read-private user-modify-playback-state user-read-playback-state",
  playerName: "MoodPad",
  sigma: 0.15,
  recentlyPlayedSize: 5,
};
