"""
data_manager.py — read and write webapp/data.js

data.js is a JavaScript file containing `window.TRACK_DATA = {...};`.
It serves two purposes:
  1. Loaded by the browser as a <script> tag (no fetch/JSON parse needed).
  2. Read back by sync.py as a cache to skip already-analyzed tracks.

The JSON object inside is extracted with a regex so we never need a JS parser.

Multi-playlist format (current):
  {
    "generated_at": "...",
    "sync_branch":  "...",
    "playlists": {
      "<playlist_id>": {
        "name": str, "synced_at": str, "sync_branch": str,
        "track_ids": [str, ...]   # ordered list, preserves Spotify order
      }
    },
    "tracks": {
      "<track_id>": { track_id, uri, title, artist, album_art_url, duration_ms,
                      [valence, energy, loudness_db, download_failed, analysis_failed] }
    }
  }

Old single-playlist format (tracks as list) is automatically migrated on read.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Regex that matches: window.TRACK_DATA = { ... };
# re.DOTALL makes '.' match newlines so it works across the multi-line JSON block.
_DATA_RE = re.compile(r"window\.TRACK_DATA\s*=\s*(\{.*?\});", re.DOTALL)

_JS_TEMPLATE = """\
// Generated by sync.py on {generated_at}
// Do not edit manually — run the "Sync Playlist" workflow to regenerate.
window.TRACK_DATA = {json_body};
"""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _migrate_old_format(data: dict) -> dict:
    """Convert the old single-playlist format (tracks as list) to multi-playlist."""
    old_tracks_list = data["tracks"]
    old_pid       = data.get("playlist_id", "unknown")
    old_name      = data.get("playlist_name", "Imported Playlist")
    old_synced_at = data.get("generated_at", "")
    old_branch    = data.get("sync_branch", "")

    tracks_dict = {
        t["track_id"]: t
        for t in old_tracks_list
        if isinstance(t, dict) and "track_id" in t
    }
    playlists_dict = {
        old_pid: {
            "name":        old_name,
            "synced_at":   old_synced_at,
            "sync_branch": old_branch,
            "track_ids": [
                t["track_id"]
                for t in old_tracks_list
                if isinstance(t, dict) and "track_id" in t
            ],
        }
    }
    return {"playlists": playlists_dict, "tracks": tracks_dict}


def _parse_raw(raw: dict) -> dict:
    """Normalize a raw parsed JSON dict to {"playlists": {...}, "tracks": {...}}."""
    # Old single-playlist format: has "playlist_name" string + "tracks" list
    if isinstance(raw.get("playlist_name"), str) and isinstance(raw.get("tracks"), list):
        return _migrate_old_format(raw)

    playlists = raw.get("playlists")
    tracks    = raw.get("tracks")
    if not isinstance(playlists, dict) or not isinstance(tracks, dict):
        return {"playlists": {}, "tracks": {}}

    return {"playlists": playlists, "tracks": tracks}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def read_data_js(path: Path) -> dict:
    """Parse data.js and return a normalized multi-playlist dict.

    Returns {"playlists": {}, "tracks": {}} if the file is missing or invalid.
    Automatically migrates the old single-playlist format.
    """
    if not path.exists():
        return {"playlists": {}, "tracks": {}}

    content = path.read_text(encoding="utf-8")
    match = _DATA_RE.search(content)
    if not match:
        return {"playlists": {}, "tracks": {}}

    try:
        raw = json.loads(match.group(1))
    except json.JSONDecodeError:
        return {"playlists": {}, "tracks": {}}

    return _parse_raw(raw)


def write_data_js(path: Path, data: dict, sync_branch: str = "") -> str:
    """Serialize `data` (with "playlists" and "tracks" keys) and write data.js.

    Sets top-level "generated_at" and "sync_branch".
    Returns the generated_at ISO timestamp string.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    output: dict[str, Any] = {
        "generated_at": generated_at,
        "sync_branch":  sync_branch,
        "playlists":    data.get("playlists", {}),
        "tracks":       data.get("tracks", {}),
    }

    json_body = json.dumps(output, indent=2, ensure_ascii=False)
    content   = _JS_TEMPLATE.format(generated_at=generated_at, json_body=json_body)
    path.write_text(content, encoding="utf-8")
    return generated_at


def update_track(path: Path, track_id: str, fields: dict) -> None:
    """Merge `fields` into tracks[track_id] in data.js.

    Used for incremental saves: after each track is analyzed its valence/energy
    are written immediately so a mid-run interruption doesn't lose progress.

    If the file or the track does not exist, this is a no-op.
    """
    if not path.exists():
        return

    content = path.read_text(encoding="utf-8")
    match = _DATA_RE.search(content)
    if not match:
        return

    try:
        raw = json.loads(match.group(1))
    except json.JSONDecodeError:
        return

    data = _parse_raw(raw)
    if track_id not in data["tracks"]:
        return

    data["tracks"][track_id].update(fields)
    write_data_js(path, data, sync_branch=raw.get("sync_branch", ""))
