"""
data_manager.py — read and write webapp/data.js

data.js is a JavaScript file containing `window.TRACK_DATA = {...};`.
It serves two purposes:
  1. Loaded by the browser as a <script> tag (no fetch/JSON parse needed).
  2. Read back by sync.py as a cache to skip already-analyzed tracks.

The JSON object inside is extracted with a regex so we never need a JS parser.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

# Regex that matches: window.TRACK_DATA = { ... };
# re.DOTALL makes '.' match newlines so it works across the multi-line JSON block.
_DATA_RE = re.compile(r"window\.TRACK_DATA\s*=\s*(\{.*?\});", re.DOTALL)

_JS_TEMPLATE = """\
// Generated by sync.py on {generated_at}
// Do not edit manually — run the "Sync Playlist" workflow to regenerate.
window.TRACK_DATA = {json_body};
"""


def read_data_js(path: Path) -> dict[str, dict]:
    """Parse an existing data.js and return a dict keyed by track_id.

    Returns an empty dict if the file does not exist or contains no valid data.
    """
    if not path.exists():
        return {}

    content = path.read_text(encoding="utf-8")
    match = _DATA_RE.search(content)
    if not match:
        return {}

    try:
        data = json.loads(match.group(1))
    except json.JSONDecodeError:
        return {}

    tracks = data.get("tracks")
    if not isinstance(tracks, list):
        return {}

    return {t["track_id"]: t for t in tracks if isinstance(t, dict) and "track_id" in t}


def write_data_js(
    path: Path,
    playlist_name: str,
    playlist_id: str,
    tracks: list[dict],
    sync_branch: str = "",
) -> str:
    """Serialize the full track list and write data.js.

    Args:
        path: Destination path (e.g. webapp/data.js).
        playlist_name: Human-readable playlist name.
        playlist_id: Spotify playlist ID.
        tracks: List of track dicts. Each must have at least 'track_id'.

    Returns:
        The generated_at ISO timestamp string.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    data: dict[str, Any] = {
        "playlist_name": playlist_name,
        "playlist_id": playlist_id,
        "generated_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "sync_branch": sync_branch,
        "tracks": tracks,
    }

    json_body = json.dumps(data, indent=2, ensure_ascii=False)
    content = _JS_TEMPLATE.format(
        generated_at=data["generated_at"],
        json_body=json_body,
    )
    path.write_text(content, encoding="utf-8")
    return data["generated_at"]


def update_track(path: Path, track_id: str, fields: dict) -> None:
    """Merge `fields` into the track with the given track_id in data.js.

    Used for incremental saves: after each track is analyzed its valence/energy
    are written immediately so a mid-run interruption doesn't lose progress.

    If the file or the track does not exist, this is a no-op.
    """
    cache = read_data_js(path)
    if track_id not in cache:
        return

    cache[track_id].update(fields)

    # Re-read the full metadata (playlist_name, playlist_id) from the file
    # so we can write it back intact.
    content = path.read_text(encoding="utf-8")
    match = _DATA_RE.search(content)
    if not match:
        return

    try:
        data = json.loads(match.group(1))
    except json.JSONDecodeError:
        return

    # Replace the track list with the updated cache values.
    # Preserve insertion order from the original list.
    original_ids = [t.get("track_id") for t in data.get("tracks", [])]
    data["tracks"] = [cache[tid] for tid in original_ids if tid in cache]
    data["generated_at"] = datetime.now(timezone.utc).isoformat(timespec="seconds")

    json_body = json.dumps(data, indent=2, ensure_ascii=False)
    new_content = _JS_TEMPLATE.format(
        generated_at=data["generated_at"],
        json_body=json_body,
    )
    path.write_text(new_content, encoding="utf-8")
